# Test 2024-04-27 at 02:23:15

name: Test

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Cpan
      run:  sudo cpan install -T Data::Dump Data::Table::Text

    - name: Java
      run:
        java PerlFromJava.java
        cat PerlFromJava.txt
